### ISSUE TITLE
想问下主要的三维高斯动态场景化的代码主要在哪里？怎么将他应用到自己的三维高斯上？Can you tell me where the main code for dynamic scene modeling using 3D Gaussian is located? How can I apply it to my own 3D Gaussian model?

### ISSUE THREAD

**Issue by huahangc** [HKU-MedAI/EndoGS#11]

**Comment by Jasloft** [comment]
Hey.I have the same question as you. Have you solved it out? The .ply file i get is not like soft tissues but random spots. i appreciate it if you have related codes that i can integrate it into my own gs model.
