### ISSUE TITLE
Gaussian deformation field network

### ISSUE THREAD

**Issue by darthandvader** [HKU-MedAI/EndoGS#2]
From the paper we know the input of Gaussian deformation field network is 3D gaussians and time stamp, but if there's only one gaussians generated from the initial point cloud, how could the deformation be predicted with only timestamp? I wonder if you guys generate different point cloud at different timestamp so we can get deformed gaussians? Thank you!

**Comment by Advocate99** [comment]
Hi, we have the initial gaussians and then deform the static field with different deformation with different timestep inputs. This part is basically the same as those works on deformable/dynamic neural field/gaussians spalatting.
