### ISSUE TITLE
train-test splitting and poses for rendering

### ISSUE THREAD

**Issue by darthandvader** [HKU-MedAI/EndoGS#4]
Could you tell me where you conduct train-test splitting and poses for rendering?  Tried to check that part but didnt figure it out

**Comment by darthandvader** [comment]
I checked the code, it's like you use all the images for training and also for testing, I'm not sure tho

**Comment by Advocate99** [comment]
Hi. Because in this dataset, all the poses can be treated the same. It is also practical to have many images from different poses at each timepoint but the dataset we use are single-viewpoint videos. And the evaluation part is the same as comparison methods.
