### ISSUE TITLE
About the evaluation results

### ISSUE THREAD

**Issue by darthandvader** [HKU-MedAI/EndoGS#5]
Hi, I repoduced the result for cutting and puliing scenes, but the quantitative matrices are lower than those in the paper, for cutting the psnr is around 36.74(without sa). I wonder if it's in the acceptable range.

**Comment by Advocate99** [comment]
Hi, the result is reasonable. We report the metrics over the whole dataset which consists of 6 videos. I checked my former metrics on this sample and the results are close to 37, also lower than the mean psnr on the whole dataset.

**Comment by darthandvader** [comment]
What about pulling? My result of pulling is not as good as the cutting, like less than 33, I'll run it again tho but kinda curious what your result on pulling(without sa)

**Comment by Advocate99** [comment]
Hi, it is a little bit strange. My result is higher than 37.

**Comment by darthandvader** [comment]
Hi, I ran it again, the result is indeed higher than 37. You are right
