### ISSUE TITLE
Evaluation result on pulling

### ISSUE THREAD

**Issue by LiuHengyu321** [HKU-MedAI/EndoGS#6]
Dear @Advocate99 and @Kyfafyd,

I use the default parameters in the given code for training and conduct evaluation on pulling. The PSNR of pulling is 35.25486373901367, I think the result maybe a litter lower, does it make sense?

Or maybe the problem the initialization with SfM? I use the auto reconstruction of COLMAP.

**Comment by LiuHengyu321** [comment]
Thank you for your reply @Advocate99！
I run this sample again and get the result below with the environment ? (ubtuntu 22.04; python 3.7; cuda 11.6).
```
PSNR:36.66530227661133
SSIM:0.9620658159255981
LPIPS:0.05415654927492142
```
A little higher than before, but still lower than 37.

**Comment by Advocate99** [comment]
I think the result is still a little bit lower but compared to the former result, this is more reasonable.

**Comment by LiuHengyu321** [comment]
Tnank you for your reply @Advocate99 !
I will try another time and on different environments.
