### ISSUE TITLE
Colmap for generating "pulling soft tissues" dataset sparse points & cam poses [No good pairs found]

### ISSUE THREAD

**Issue by SimonHanYANG** [HKU-MedAI/EndoGS#7]
Hi,

Very good work!

When I use Colmap Win GUI for generating "pulling soft tissues" poses and cam poses, finally output **"No good initial image pair"**

Maybe the tissues have less texture. Cannot find good feature matching?

Is that normal? Can I still use these cam poses for training? or Are there any methods for refining?

> Additional: I found "poses_bounds.npy" in the original "EndoNeRF Dataset". Can I just use this cam poses? It seems to just have an identical matrix in it.

![colmap_pulling](https://github.com/HKU-MedAI/EndoGS/assets/124108306/3d537467-21d9-4c8c-8390-385ecda471c5)

**Comment by Advocate99** [comment]
Hi, sorry for the late reply.
I have not encountered that. Could you try check the process metioned here https://github.com/HKU-MedAI/EndoGS/issues/3 ? I have not try that on windows. Let me know if it can be solved, thanks.
