### ISSUE TITLE
如何使用colmap初始化点云？   How to initialize point clouds using colmap？

### ISSUE THREAD

**Issue by swc-123** [HKU-MedAI/EndoGS#8]
你好，请问endonerf数据集如何使用colmap进行初始化点云，我看他有两组图像还有深度图等等，我有点不知道怎么操作了。
Hello, could you please tell me how to use the endonerf dataset to initialize point clouds with colmap? I noticed that it consists of two sets of images and depth maps, but I'm unsure about the specific steps involved.

**Comment by Advocate99** [comment]
你好，我们只需要用其中一组图像就可以进行初始化，这里面有截图https://github.com/HKU-MedAI/EndoGS/issues/3.
Hi, we only need to use one set of images to initialize and here is the screenshot of the operation:https://github.com/HKU-MedAI/EndoGS/issues/3.
