### ISSUE TITLE
CUDA error: device-side assert triggered

### ISSUE THREAD

**Issue by neneyork** [HKU-MedAI/EndoGS#9]
Hi, thanks for your work in surgical scene reconstruction. I am implementing the sdf loss and normal loss on my model. Howeve, there occors an error: 'CUDA error: device-side assert triggered' in the 'get_field_values' method. I wonder if you also met this problem in implementation and how you solved it. Thanks for you patience!

`  File "/root/autodl-tmp/Deformable-3D-Gaussians/train.py", line 12, in <module>
    import os

  File "/root/autodl-tmp/Deformable-3D-Gaussians/train.py", line 174, in training
    opacity=opacities

  File "/root/autodl-tmp/Deformable-3D-Gaussians/scene/gaussian_model.py", line 527, in get_field_values
    densities[density_mask] = densities[density_mask] / (densities[density_mask].detach() + 1e-12)

RuntimeError: CUDA error: device-side assert triggered

CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.`

**Comment by Advocate99** [comment]
Hi, sorry I have not encountered that.
Does this error happen at the beginning of the training or during the training?
Maybe try changing the running environments.

**Comment by neneyork** [comment]
@Advocate99 It occurs during the training, 1000 iterations after the method is called. Thanks, I would try to changing the environment.

**Comment by Advocate99** [comment]
Hi, it seems that you build your model on Deformable-3D-Gaussians. 
You may also have an issue there. My code is built upon 4dgs though they are similar. Maybe it is due to env and maybe it is not. 1000 iters after training indicates it happens at a certain operation and you may check in that way.

**Comment by neneyork** [comment]
Hi, this is caused by 'gaussians.knn_idx' is not updated after the densification and prune, resulting 'index out of bound'. Apply 'reset_neighbors' after densification can fix this error. Thanks for your help!
